version: "3"

services:
  mariadb:
    image: mariadb:10.5.2
    container_name: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MATOMO_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MATOMO_DB_NAME}
      MYSQL_USER: ${MATOMO_DB_USER}
      MYSQL_PASSWORD: ${MATOMO_DB_PASSWORD}
    networks:
      - internal
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      interval: 10s
      timeout: 5s
      retries: 5

  matomo:
    image: matomo:4.4.1-apache
    container_name: matomo
    restart: always
    links:
      - mariadb
    volumes:
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs
      - ./php.ini:/usr/local/etc/php/php.ini
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=${MATOMO_DB_USER}
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DB_PASSWORD}
      - MATOMO_DATABASE_DBNAME=${MATOMO_DB_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Service
      - "traefik.http.routers.matomo.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.matomo.entrypoints=websecure"
      - "traefik.http.routers.matomo.service=matomo"
      - "traefik.http.services.matomo.loadbalancer.server.port=80"
    networks:
      - internal
      - traefik

volumes:
  db:
  matomo:

networks:
  internal:
    external: false
    driver: bridge
  traefik:
    external: true
